name: Checkov Docker Scan

 

on: [push]

 

jobs:

  checkov_scan:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v4

    - name: Set up Python

      uses: actions/setup-python@v4

      with:

        python-version: '3.x'

    - name: Install Checkov

      run: |

        python -m pip install --upgrade pip

        pip install checkov

    - name: Run Checkov scan

      run: |

        checkov -d . - o sarif -- output-file-path results.sarif
          
    - name: send curl
      run: |
       curl -X POST -H "Content-Type: multipart/form-data" -F "file=@results.json"  http://3y9ock8c44xj7mramywx2.appsecengineer.training:8880/callback
 
