name: Checkov Docker Scan

on: [push]

jobs:

  checkov_scan:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

    - name: Set up Python

      uses: actions/setup-python@v2

      with:

        python-version: '3.x'

    - name: Install Checkov
      run: |

        python -m pip install --upgrade pip

        pip install checkov

    - name: Run Checkov scan

      run: |
        checkov -d .  --output-file-path results.sarif --output-format sarif || true
    - name: convert
      run: |
        python convert_sarif_to_json.py
