name: Checkov Docker Scan

on: [push]

jobs:

  checkov_scan:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

    - name: Set up Python

      uses: actions/setup-python@v2

      with:

        python-version: '3.x'

    - name: Install Checkov
      run: |

        python -m pip install --upgrade pip

        pip install checkov

    - name: Run Checkov scan

      run: |
        checkov -d . -o sarif --output-file-path results.sarif || true
        
    - name: view Json
      run: |
        cp -r /home/runner/work/checkof/checkof/results.sarif  /home/runner/work/checkof/checkof/results.json
           
    - name: send curl
      run: |
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@results.json"  http://3y9ock8c44xj7mramywx2.appsecengineer.training:8880/callback
